import React from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Card } from '@/components/Card';
import { ProgressBar } from '@/components/ProgressBar';
import { CircularProgress } from '@/components/CircularProgress';
import { colors, typography, spacing, radii } from '@/theme';

// ---- MOCK DATA ----
// Replaced with real values from GET /api/nutrition/daily once Phase 11
// (Nutrition Calculation Engine) exists. Shape is deliberately written
// to already match what that endpoint will realistically return, so the
// swap later is just changing where this object comes from.
const mockDaily = {
  targetCalories: 2100,
  eatenCalories: 1480,
  burnedCalories: 340,
  streakDays: 5,
  macros: [
    { key: 'protein', label: 'Protein', icon: 'egg-outline' as const, current: 68, target: 95, unit: 'g' },
    { key: 'carbs', label: 'Carbs', icon: 'barley' as const, current: 185, target: 260, unit: 'g' },
    { key: 'fat', label: 'Fat', icon: 'water-outline' as const, current: 44, target: 65, unit: 'g' },
    { key: 'fibre', label: 'Fibre', icon: 'leaf' as const, current: 26, target: 32, unit: 'g' },
  ],
  meals: [
    { key: 'breakfast', label: 'Breakfast', logged: true, kcal: 420, tag: 'High Protein' },
    { key: 'lunch', label: 'Lunch', logged: true, kcal: 680, tag: '+9.2g Fibre' },
    { key: 'snack', label: 'Snack', logged: true, kcal: 150, tag: 'Low GI snack' },
    { key: 'dinner', label: 'Dinner', logged: false, kcal: null, tag: 'Target ~600 kcal' },
  ],
  hydrationLitres: 1.75,
  hydrationTargetLitres: 2.5,
};

export function TodayDashboardScreen() {
  const remaining = mockDaily.targetCalories - mockDaily.eatenCalories + mockDaily.burnedCalories;
  const calorieProgress = mockDaily.eatenCalories / mockDaily.targetCalories;

  return (
    <SafeAreaView style={styles.screen} edges={['top']}>
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <View>
            {/* MOCK: name and date become real once the profile/daily endpoints feed this screen */}
            <Text style={styles.greeting}>Good afternoon, Kavindi</Text>
            <Text style={styles.date}>Thursday, Oct 24</Text>
          </View>
          <View style={styles.streakBadge}>
            <MaterialCommunityIcons name="fire" size={14} color={colors.onSecondaryFixed} />
            <Text style={styles.streakText}>{mockDaily.streakDays} Days</Text>
          </View>
        </View>

        <Card style={styles.gaugeCard}>
          <View style={styles.gaugeHeader}>
            <Text style={styles.cardTitle}>Daily Fuel Gauge</Text>
            <Text style={styles.cardSubtitle}>Target: {mockDaily.targetCalories.toLocaleString()} kcal</Text>
          </View>
          <View style={styles.gaugeRow}>
            <CircularProgress progress={calorieProgress} size={150} strokeWidth={14}>
              <Text style={styles.gaugeNumber}>{remaining.toLocaleString()}</Text>
              <Text style={styles.gaugeUnit}>kcal left</Text>
            </CircularProgress>
            <View style={styles.gaugeStats}>
              <View>
                <Text style={styles.gaugeStatLabel}>Eaten</Text>
                <Text style={styles.gaugeStatValue}>{mockDaily.eatenCalories.toLocaleString()}</Text>
                <Text style={styles.gaugeStatUnit}>kcal</Text>
              </View>
              <View style={{ marginTop: spacing.md }}>
                <Text style={styles.gaugeStatLabel}>Burned</Text>
                <Text style={styles.gaugeStatValue}>{mockDaily.burnedCalories}</Text>
                <Text style={styles.gaugeStatUnit}>kcal</Text>
              </View>
            </View>
          </View>
        </Card>

        <Card style={{ marginTop: spacing.sm }}>
          <View style={styles.gaugeHeader}>
            <Text style={styles.cardTitle}>Nutritional Balance</Text>
            <Text style={styles.balancedPill}>Balanced</Text>
          </View>
          {mockDaily.macros.map((macro) => (
            <View key={macro.key} style={styles.macroRow}>
              <MaterialCommunityIcons name={macro.icon} size={18} color={colors.secondary} />
              <Text style={styles.macroLabel}>{macro.label}</Text>
              <View style={{ flex: 1 }}>
                <ProgressBar progress={macro.current / macro.target} />
              </View>
              <Text style={styles.macroValue}>
                {macro.current}{macro.unit} / {macro.target}{macro.unit}
              </Text>
            </View>
          ))}
        </Card>

        {/* MOCK: AI insight text is generated by the backend in Phase 13 */}
        <View style={styles.aiInsight}>
          <MaterialCommunityIcons name="creation" size={18} color={colors.primary} />
          <View style={{ flex: 1 }}>
            <Text style={styles.aiInsightLabel}>AI INSIGHT · Lentil boost</Text>
            <Text style={styles.aiInsightBody}>
              Great job adding dhal curry at lunch! That gave you{' '}
              <Text style={{ fontWeight: '700' }}>9.2g of fibre</Text>, putting you right on
              track for your 30g daily target.
            </Text>
          </View>
        </View>

        <View style={styles.mealsHeader}>
          <Text style={styles.cardTitle}>Today's Meals</Text>
          <Text style={styles.cardSubtitle}>
            {mockDaily.meals.filter((m) => m.logged).length} of {mockDaily.meals.length} logged
          </Text>
        </View>

        {mockDaily.meals.map((meal) => (
          <Card key={meal.key} style={{ marginBottom: spacing.sm }}>
            <View style={styles.mealRow}>
              <View style={{ flex: 1 }}>
                <View style={styles.mealTitleRow}>
                  <Text style={styles.mealTitle}>{meal.label}</Text>
                  {meal.logged && (
                    <MaterialCommunityIcons name="check-circle" size={16} color={colors.primary} />
                  )}
                </View>
                <Text style={styles.mealTag}>
                  {meal.logged ? `${meal.kcal} kcal · ${meal.tag}` : meal.tag}
                </Text>
              </View>
              {!meal.logged && (
                <Pressable style={styles.logButton}>
                  <MaterialCommunityIcons name="plus" size={16} color={colors.onPrimary} />
                  <Text style={styles.logButtonText}>Log {meal.label}</Text>
                </Pressable>
              )}
            </View>
          </Card>
        ))}

        <Card>
          <View style={styles.mealRow}>
            <MaterialCommunityIcons name="cup-water" size={22} color={colors.secondary} />
            <View style={{ flex: 1, marginLeft: spacing.sm }}>
              <Text style={styles.mealTitle}>Hydration</Text>
              <Text style={styles.mealTag}>
                {mockDaily.hydrationLitres} / {mockDaily.hydrationTargetLitres}L
              </Text>
            </View>
            <Pressable style={styles.hydrationAdd}>
              <MaterialCommunityIcons name="plus" size={18} color={colors.primary} />
            </Pressable>
          </View>
          <ProgressBar
            progress={mockDaily.hydrationLitres / mockDaily.hydrationTargetLitres}
            color={colors.secondary}
          />
        </Card>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  content: { padding: spacing.margin, gap: spacing.sm, paddingBottom: spacing.xl },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  greeting: { ...typography.headlineMd, color: colors.onSurface },
  date: { ...typography.bodySm, color: colors.onSurfaceVariant, marginTop: 2 },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.secondaryFixed,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
  },
  streakText: { ...typography.labelSm, color: colors.onSecondaryFixed },
  gaugeCard: { alignItems: 'stretch' },
  gaugeHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm },
  cardTitle: { ...typography.headlineMd, fontSize: 16, color: colors.onSurface },
  cardSubtitle: { ...typography.labelSm, color: colors.onSurfaceVariant },
  balancedPill: {
    ...typography.labelSm,
    color: colors.primary,
    backgroundColor: colors.surfaceContainer,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radii.pill,
  },
  gaugeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  gaugeNumber: { ...typography.headlineLg, fontSize: 30, color: colors.onSurface },
  gaugeUnit: { ...typography.labelSm, color: colors.onSurfaceVariant },
  gaugeStats: { gap: spacing.sm },
  gaugeStatLabel: { ...typography.labelSm, color: colors.onSurfaceVariant },
  gaugeStatValue: { ...typography.headlineMd, fontSize: 20, color: colors.onSurface },
  gaugeStatUnit: { ...typography.labelSm, color: colors.onSurfaceVariant },
  macroRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: spacing.xs },
  macroLabel: { ...typography.labelMd, color: colors.onSurface, width: 56 },
  macroValue: { ...typography.labelSm, color: colors.onSurfaceVariant, width: 78, textAlign: 'right' },
  aiInsight: {
    flexDirection: 'row',
    gap: spacing.sm,
    backgroundColor: colors.surfaceContainerLow,
    padding: spacing.sm,
    borderRadius: radii.md,
  },
  aiInsightLabel: { ...typography.labelSm, color: colors.primary, marginBottom: 2 },
  aiInsightBody: { ...typography.bodySm, color: colors.onSurfaceVariant },
  mealsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.xs },
  mealRow: { flexDirection: 'row', alignItems: 'center' },
  mealTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  mealTitle: { ...typography.labelLg, color: colors.onSurface },
  mealTag: { ...typography.bodySm, color: colors.onSurfaceVariant, marginTop: 2 },
  logButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.pill,
  },
  logButtonText: { ...typography.labelSm, color: colors.onPrimary },
  hydrationAdd: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
